config/routes.rb
TapcoSyncer::Application.routes.draw do
  resources :api_calls

end

app/models/api_call.rb
class ApiCall < ActiveRecord::Base
  attr_accessible :call_time, :url, :result

  before_save :call_api

  def call_api
    self.url = "https://tapco.secure.force.com/DistributorLocator/services/apexrest/findnearby/post"
    apiResult = HTTParty.post(self.url, :body => {})
    self.result = apiResult.response.code
    self.call_time = Time.now
  end

end

app/controllers/api_calls_controller.rb
class ApiCallsController < ApplicationController
  # GET /api_calls
  # GET /api_calls.json
  def index
    @api_calls = ApiCall.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @api_calls }
    end
  end

  # GET /api_calls/1
  # GET /api_calls/1.json
  def show
    @api_call = ApiCall.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @api_call }
    end
  end

  # GET /api_calls/new
  # GET /api_calls/new.json
  def new
    @api_call = ApiCall.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api_call }
    end
  end

  # GET /api_calls/1/edit
  def edit
    @api_call = ApiCall.find(params[:id])
  end

  # POST /api_calls
  # POST /api_calls.json
  def create
    @api_call = ApiCall.new(params[:api_call])

    respond_to do |format|
      if @api_call.save
        format.html { redirect_to @api_call, notice: 'Api call was successfully created.' }
        format.json { render json: @api_call, status: :created, location: @api_call }
      else
        format.html { render action: "new" }
        format.json { render json: @api_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /api_calls/1
  # PUT /api_calls/1.json
  def update
    @api_call = ApiCall.find(params[:id])

    respond_to do |format|
      if @api_call.update_attributes(params[:api_call])
        format.html { redirect_to @api_call, notice: 'Api call was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_call.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api_calls/1
  # DELETE /api_calls/1.json
  def destroy
    @api_call = ApiCall.find(params[:id])
    @api_call.destroy

    respond_to do |format|
      format.html { redirect_to api_calls_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/api_calls_helper.rb
module ApiCallsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/api_calls/_form.html.erb
<%= form_for(@api_call) do |f| %>
  <% if @api_call.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@api_call.errors.count, "error") %> prohibited this api_call from being saved:</h2>

      <ul>
      <% @api_call.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/api_calls/edit.html.erb
<h1>Editing api_call</h1>

<%= render 'form' %>

<%= link_to 'Show', @api_call %> |
<%= link_to 'Back', api_calls_path %>

app/views/api_calls/index.html.erb
<h1>Listing api_calls</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Call time</th>
    <th>Result</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @api_calls.each do |api_call| %>
  <tr>
    <td><%= api_call.url %></td>
    <td><%= api_call.call_time %></td>
    <td><%= api_call.result %></td>
    <td><%= link_to 'Show', api_call %></td>
    <td><%= link_to 'Edit', edit_api_call_path(api_call) %></td>
    <td><%= link_to 'Destroy', api_call, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Api call', new_api_call_path %>

app/views/api_calls/new.html.erb
<h1>New api_call</h1>

<%= render 'form' %>

<%= link_to 'Back', api_calls_path %>

app/views/api_calls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @api_call.url %>
</p>

<p>
  <b>Call time:</b>
  <%= @api_call.call_time %>
</p>


<%= link_to 'Edit', edit_api_call_path(@api_call) %> |
<%= link_to 'Back', api_calls_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TapcoSyncer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>